Update gaussian_cantours.jl
When I run this code, there is 
LoadError: MethodError: meshgrid has no method matching meshgrid(::LinSpace{Float64}, ::LinSpace{Float64}).

The problem might be derived from line 9 " Quick meshgrid function " : 
"
meshgrid(x::Vector, y::Vector) = (repmat(x, 1, length(y))',
repmat(y, 1, length(x)))
"
which is not consistent with 
"
x_grid = linspace(-1.5, 2.9, 100)
y_grid = linspace(-3.1, 1.7, 100)
X, Y = meshgrid(x_grid, y_grid) .
"
Thus, regarding defining "meshgrid function", this one

meshgrid(x::LinSpace, y::LinSpace) = (repmat(x, 1, length(y))',
repmat(y, 1, length(x)))
works.