Update lqcontrol_solutions_jl.ipynb
Firstly, when I run the original code in this file, there was a warning:
"
LoadError: MethodError: `convert` has no method matching convert(::Type{QuantEcon.LQ}, ::Float64, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,1}, ::Array{Float64,1}, ::Float64, ::Int64, ::Array{Float64,2})
This may have arisen from a call to the constructor QuantEcon.LQ(...),
since type constructors fall back to convert methods.
"
It has been fixed now in this updated version.

However, there still is a coding problem that " LoadError: DimensionMismatch("arrays could not be broadcast to a common size") ".

After checking other key terms (i.e. assets and consumption), I think this problem might be raised from the constructors of "w_path" and "income" (same as in the lq_permanent_1.jl). Could you please help to have a look? Thanks so much in advance!